#
# Makefile
#

CC = gcc

# CAUTION: Always use '-pthread' when compiling POSIX threads-based
# applications, instead of linking with "-lpthread" directly.
CFLAGS = -Wall -O2 -pthread
LIBS =

all: pthread-test simplesync-mutex simplesync-atomic kgarten mandel mandel_old ex1-mutex ex1-mutex.s  ex1-atomic ex1-atomic.s

## Ex1 (two versions)
ex1-mutex: ex1-mutex.o
        $(CC) $(CFLAGS) -o ex1-mutex ex1-mutex.o $(LIBS)

ex1-atomic: ex1-atomic.o
        $(CC) $(CFLAGS) -o ex1-atomic ex1-atomic.o $(LIBS)

ex1-mutex.o: ex1.c
        $(CC) $(CFLAGS) -DSYNC_MUTEX -c -o ex1-mutex.o ex1.c

ex1-atomic.o: ex1.c
        $(CC) $(CFLAGS) -DSYNC_ATOMIC -c -o ex1-atomic.o ex1.c

ex1-atomic.s: ex1.c
        $(CC) $(CFLAGS) -DSYNC_ATOMIC -S -g -o ex1-atomic.s ex1.c

ex1-mutex.s: ex1.c
        $(CC) $(CFLAGS) -DSYNC_MUTEX -S -g -o ex1-mutex.s ex1.c

## Pthread test
pthread-test: pthread-test.o
        $(CC) $(CFLAGS) -o pthread-test pthread-test.o $(LIBS)

pthread-test.o: pthread-test.c
        $(CC) $(CFLAGS) -c -o pthread-test.o pthread-test.c

## Simple sync (two versions)
simplesync-mutex: simplesync-mutex.o
        $(CC) $(CFLAGS) -o simplesync-mutex simplesync-mutex.o $(LIBS)

simplesync-atomic: simplesync-atomic.o
        $(CC) $(CFLAGS) -o simplesync-atomic simplesync-atomic.o $(LIBS)

simplesync-mutex.o: simplesync.c
        $(CC) $(CFLAGS) -DSYNC_MUTEX -c -o simplesync-mutex.o simplesync.c

simplesync-atomic.o: simplesync.c
        $(CC) $(CFLAGS) -DSYNC_ATOMIC -c -o simplesync-atomic.o simplesync.c

## Kindergarten
kgarten: kgarten.o
        $(CC) $(CFLAGS) -o kgarten kgarten.o $(LIBS)

kgarten.o: kgarten.c
        $(CC) $(CFLAGS) -c -o kgarten.o kgarten.c


## Mandel
mandel: mandel-lib.o mandel.o
        $(CC) $(CFLAGS) -o mandel mandel-lib.o mandel.o $(LIBS)

mandel-lib.o: mandel-lib.h mandel-lib.c
        $(CC) $(CFLAGS) -c -o mandel-lib.o mandel-lib.c $(LIBS)

mandel.o: mandel.c
        $(CC) $(CFLAGS) -c -o mandel.o mandel.c $(LIBS)

##Mandel_old
mandel_old: mandel-lib.o mandel_old.o
                $(CC) $(CFLAGS) -o mandel_old mandel-lib.o mandel_old.o $(LIBS)

mandel-lib.o: mandel-lib.h mandel-lib.c
                $(CC) $(CFLAGS) -c -o mandel-lib.o mandel-lib.c $(LIBS)

mandel_old.o: mandel_old.c
                $(CC) $(CFLAGS) -c -o mandel_old.o mandel_old.c $(LIBS)


clean:
        rm -f *.s *.o pthread-test simplesync-{atomic,mutex} kgarten mandel mandel_old ex1-{atomic,mutex}
 